language: rust
rust:
  - stable
  - nightly
matrix:
  include:
    - rust: stable
    - rust: nightly
    - rust: nightly
      env:
       - FEATURES='nightly'
  fast_finish: true
script:
  - cargo build --verbose --features "$FEATURES" &&
  - cargo test --verbose --features "$FEATURES"
